name = input("введи имя ")
age = int(input("введи возраст "))
city = input("введи город ")
print("Метод раз")
print("Привет {}, ты такой старый, тебе аж {}, и живёшь в {}, а это жопа мира".format(name, age, city))
print("Метод два")
print("Привет %(name)s, ты такой старый, тебе аж %(age)d, и живёшь в %(city)s, а это жопа мира" % {"name": name, "age": age, "city": city})
print("Метод два")
print(f"Привет {name}, ты такой старый, тебе аж {age}, и живёшь в {city}, а это жопа мира")
